static const char* AMOGUS =
"                  .^^^^^^^^^^.                    \n"
"             :~JPB&@@@@@@@@@@&G?^                 \n"
"          .7P&@@@&&###B#BBBB#&@@&G!               \n"
"        .?#@@@#BGGGGGGGGGGGGGGGB&@@7              \n"
"        5@@@@########BBBGGGGGGGGB@@@7             \n"
"     .!P@@@@&######&@@@@@&&BGGGGGB@@&:            \n"
"    ^G@@B57!^:...:~!77?YB@@@BGGGGB&@@?            \n"
"   ~&@B?~.    ....^~~~~J5G@@#GGGGG#@@B^^:.        \n"
"  .G@&?~~~~~~~~~~~~~~!J55G@@#GGGGBB&@@@@&#BP?.    \n"
"  .#@@PYYJJJJJ?????JY5555#@@#GGGGBB#@@#B##&@@G.   \n"
"   7@@@#GPP55555555555PG#@@&GGGGGBB&@@#GGGG@@@7   \n"
"    ~B@@@@&##BGGGGGBB#@@@@&GGGGGGBB#@@&BBBB&@@7   \n"
"     J@@#B#&&&@@@@@@@@&&#BGGGGGGGBB#@@&BBBB#@@J   \n"
"     P@@BGGGGGGGBBBBBGGGGGGGGGGGBBB#@@&BBBB#@@P   \n"
"    :&@@#GGGGGGGGGGGGGGGGGGGGGGGBBB#@@&BBBB#@@G.  \n"
"    ^@@@#GGGGGGGGGGGGGGGGGGGGGGBBBB#@@&BBBB#@@#.  \n"
"    ^&@@#BGGGGGGGGGGGGGGGGGGGGBBBBB#@@&BBBB#@@&.  \n"
"    .B@@#BBGGGGGGGGGGGGGGGGGGBBBBBB#@@&BBBB#@@#.  \n"
"     ?@@&BBBBBBBBGGGGGBBBBBBBBBBBBB#@@&BBBB#@@5   \n"
"     ^&@@BBBBBBBBBBBBBBBBBBBBBBBBBB#@@#BBB#&@&^   \n"
"      G@@#BBB#########&&##BBBBBBBBB&@@&&&@@@&7    \n"
"      J@@&BBB##&@@@@&#&@@&BBBBBBBBB@@@BGGGP7:     \n"
"      :&@@#BBBBBB@@@7 7@@@BBBBBBBB#@@B.           \n"
"      .G@@#BBBBBB&@@^ !@@@BBBBBBBB#@@G            \n"
"       ~&@&#####&@@G~~?@@@#BBBBBBB&@@J            \n"
"   :~7JYG&&@@@@@@&#GBBB&@@@&#####&@@@GYJ7~:       \n"
"   ?GBBBBBBBBBBBBGGGGGGGB#&@@@@@@@&&#BBBBG?       \n"
"    :^!7?JJ55PPPGGGGGGGGGGGGGGGGP55YJ?7~^:        \n"
"             ...::::::::::::::...                 \n";

